import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is generated from the docs/ folder structure.
// Order inside a folder: `sidebar_position` front matter, or `_category_.json`.
const sidebars: SidebarsConfig = {
  kbSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
